#!/bin/bash
sudo yum update
sudo yum -y install docker
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo chkconfig docker on
sudo pip3 install docker-compose
sudo docker swarm init --advertise-addr $(hostname -i)

#Then run docker swarm join-token worker -q 
#to retrieve the join token needed.



#This script is for Amazon Linux 2
