#!/bin/bash
sudo yum update -y
sudo yum -y install docker
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo chkconfig docker on

# Retrieve join token
JOIN_COMMAND=$(docker swarm join-token worker -q)

# Join worker nodes to the Swarm
for i in {1..3}; do
    WORKER_IP="worker-$i-private-ip" # replace with the actual private IP address of the worker node
    ssh -o "StrictHostKeyChecking=no" $WORKER_IP "sudo $JOIN_COMMAND"
done
